### ISSUE TITLE
Update Forecastie at Google Play

### ISSUE THREAD

**Issue by FridoDeluxe** [martykan/forecastie#237]
I've found https://play.google.com/store/apps/details?id=com.casticalabs.forecastie on Google Play, which seems to be the official app by @martykan. Unfortunately it is version 1.2 from one year ago. I think it should be updated to the current version, so that also users without F-Droid can enjoy the newest Forecastie.

**Comment by robinpaulson** [comment]
I don't know how the Google Play updates work and personally I'm not interested in that store - Google is a horrendous all-dominating behemoth and encouraging any use of their services is immoral as far as I'm concerned, which is why I focus on F-Droid releases. Martykan may be interested in doing this, I'll leave it with him.

**Comment by ildar** [comment]
If update suspended by purpose, I suggest updating the description there.

**Comment by realmain** [comment]
It is also advertised on http://castica.tech to download this app via Github or Google Play (No F-Droid?). I for one agree that if there will no longer be updated on Google Play, it should be added to the description. 

Though, keeping it updated on Google Play would allow more exposure for this app.

**Comment by realmain** [comment]
#244 is an example of an issue that can happen to users regarding this.

**Comment by realmain** [comment]
Per Martykan:

> I will update it on Google Play this evening.

**Comment by martykan** [comment]
Done. I'll try to publish new releases more promptly in the future.
