### ISSUE TITLE
If the API key is invalid: results in "There is something wrong with your Internet connection".

### ISSUE THREAD

**Issue by dennisguse** [martykan/forecastie#251]
Yesterday, I changed my API key and missed one digit.
As a result, Forecastie complained that "There is something wrong with your Internet connection" with a Toast message.
This message was not really helpful.
Correcting the API key, fixed my issue.

Probable solution: 
I think that the parsing  of the response is too generic.
On invalid API key, OpenWeather reacts with HTTP 401 
`{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}`

Thus, parsing could account for 401 here:
https://github.com/martykan/forecastie/blob/master/app/src/main/java/cz/martykan/forecastie/tasks/GenericRequestTask.java#L99

Version 1.5 (Fdroid)

**Comment by robinpaulson** [comment]
Yes, this is a problem. I saw it last week, but didn't think to put it here. Well spotted.

We should update the text, something like:
"The API key you entered is wrong, please check and try again"

Suggestions for modification to that text please.

**Comment by realmain** [comment]
"Current API key is invalid, please try again."

Nice and simple

**Comment by nazar-pc** [comment]
I have "There is something wrong with your Internet connection" with valid API key that worked fine before. Also I've issues another key and having the same issue.
Have you experienced this?
Also 1.5 from F-Droid.

**Comment by wohali** [comment]
I'm having the same thing as @nazar-pc for about the same number of days now. Weather hasn't updated since middle of last week, and I keep getting "There is something wrong with your Internet connection." Checked that my key is valid, too.

**Comment by flocke** [comment]
Yeah, I got the same problem with a valid API key as well. What I noticed is that it only happens when I search for locations with Umlauts (äöü) in them. Everything else seems OK.

**Comment by flocke** [comment]
I just tried to search the same location on the OpenWeatherMap site directly and it was not found either. So at least my problem seems to be an issue on OpenWeatherMaps side.
But nevertheless the error messages should be improved.

**Comment by nazar-pc** [comment]
Interesting, hyphen `-` also causes issues, while name with only Latin characters is fine

**Comment by flocke** [comment]
It appears OpenWeatherMaps fixed the issue. I can now successfully search cities with Umlauts again. Could someone else confirm this?

**Comment by ramack** [comment]
seems to work for me.

**Comment by robinpaulson** [comment]
New release 1.6 will partly fix this, but we should provide a more precise error code. I have a feeling there is currently a single error code for more than one problem. Any idea how to split them into two so we can provide a useful, different, response for each?

**Comment by andrei91ro** [comment]
The issue that @nazar-pc  noted is still happening on version 1.6.1 also with a valid key.
From what I see in the source code, the app does not differentiate between error codes received from the API.
Maybe we should create a mapping between OpenWeatherMap error codes and ExceptionIDs and also a mapping between ExceptionsIDs and Exceptions Error messages.
That way, all IFs would be avoided.

Also, the App should inform the user, either at first startup or on the readme page on Gplay that it REQUIRES an API key to function.

Otherwise, it is a very good app and I congratulate the developers.

**Comment by robinpaulson** [comment]
This is an excellent suggestion @andrei91ro . Are you prepared to look through the code and start this off? This is relatively high priority, currently the error messages are confusing at best.

**Comment by robinpaulson** [comment]
Marvellous, do let us know how that goes.

**Comment by andrei91ro** [comment]
I received the following response from OpenWeatherMap. They said that these are the main error codes.

```
401 – “Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.”
404 – “city not found”
429 – API key blocked
500 – internal server error
```

**Comment by robinpaulson** [comment]
PArt of this was fixed with a new API key, the rest has been collated with similar bugs in #316 . Closing

**Comment by FridoDeluxe** [comment]
With https://github.com/martykan/forecastie/pull/479/commits/3928e355c05d807c84152f2033444226c4190ca0 a wrong API key is now handled explicitly while reading a OWM response and a dedicated error message is displayed.

Of course we could check somehow if an API key is valid directly when it's entered. But it's more important to handle invalid API keys when reading the OWM responses, because keys that were once valid might become invalid later on.

**Comment by robinpaulson** [comment]
> a wrong API key is now handled explicitly while reading a OWM response

excellent.
