### ISSUE TITLE
Custom date format causes crashes

### ISSUE THREAD

**Issue by brortao** [martykan/forecastie#287]
If you enter a custom date format, Forecastie crashes. Whenever you open the settings page to change it back, it crashes again. The only fix is to reinstall the app.

The date format I used was `%E %y-%M-%D %H:%m`. Maybe the percent symbols caused the bug, I'm not sure.

**Comment by hugomg** [comment]
I also get crashes after changing to a custom date format. I used `EEEE MMMM dd`.

After I configured a custom date format, the app widget stopped working (shows a blank blue rectangle only) and trying to launch Forecastie via the widget crashes the app. Launching Forecastie via the app icon still worked though (and the custom date format is applied correctly in this case)..

**Comment by hugomg** [comment]
After inspecting the source code, it seems that at least in my case the crash is due to the behaviour in [line 69](https://github.com/martykan/forecastie/blob/3ea4472b99d03aa5511e4bd50f65d21a55f739f6/app/src/main/java/cz/martykan/forecastie/widgets/TimeWidgetProvider.java#L69) of TimeWidgetProvider.java:

    dateFormat = dateFormat.substring(0, dateFormat.indexOf("-")-1);

Apparently, Forecastie assumes that the dateformat string has a "day part" followed by an "hours and minutes part" and that these two parts are separated by ` - `. One workaround that worked for me was changing my custom data format to `EEEE MMMM dd - HH:mm`.

**Comment by robinpaulson** [comment]
Thanks for debugging the source of the problem @hugomg . I think this is related to a previous bug, #219 , but we appeared to have fixed the issue.... Hmm, I'm not sure. More testing perhaps.

**Comment by hugomg** [comment]
Git blame says that the offending line has been there for two years, before bug #219 was reported:  https://github.com/martykan/forecastie/commit/fc1fdadf614d3325b78148cd07107c6da7c505e8

One possibility is that the people who reported that bug though the problem was with the format specifiers and didn't realize that it was actually connected to the hyphen (which is a format restriction imposed by the forecastie application logic, not by Java)

**Comment by robinpaulson** [comment]
Got it. Are there any useful reasons for the hyphen? Could it be removed entirely do you think?

**Comment by hugomg** [comment]
The ptoblem is not really the hyphen, but what forecastie is doing with it. Trying to parse or manipulate a date formate string is inherently bug prone.

Inside the app, forecastie shows dates including the time of day (since it displays one forecast for every 3 hour period). Meanwhile, on the widget, forecastie splits the time of day and date into two separate lines. If forecastie's widget just reused the same format string it uses inside the app it would end up showing the date string twice. The kludgy solution right now is to remove the hours part of the date format string by splitting at the hyphen. This crashes horribly if the custom format string is not in the same format as the default ones (with the hyphen)

One option would be to change the settings to have a format string for the date part and a format string for the hours part. The widget would display each of these parts on a separate line and the daily forecast screen would display them separated by a hyphen. This would remove the bug-prone logic entirely.

**Comment by robinpaulson** [comment]
Interesting, thanks for that explanation hugomg. I think your suggestion has merit. Does anyone else have any suggestions for fixing it? I'll have a think, this should be a relatively simple fix once we settle on a method.

**Comment by pard68** [comment]
Looks like issue #272 may be relevant. appears Android has a builtin to assist with parsing a string and getting the date format from it

**Comment by robinpaulson** [comment]
@pard68 Would you be able to supply some more info on this, perhaps some code? Cheers

**Comment by robinpaulson** [comment]
Apparently (from #272), this is useful:
https://developer.android.com/reference/java/text/DateFormat#getDateInstance(int)

If anyone is willing to use that, I'd accept a PR.

**Comment by robinpaulson** [comment]
Fixed with #365
