### ISSUE TITLE
Can't load any data anymore (since 26 of October 2018)

### ISSUE THREAD

**Issue by apteryks** [martykan/forecastie#292]
I get the "There is a problem with your internet connection" message that pops at the bottom of the app anytime I try to refresh the data.

I thought that maybe the API key of Forecastie had expired, so I created an account at openweathermap.org and got a fresh API key that I tried using, but the result is the same.

Any idea what could be going on?

**Comment by Apteryks** [comment]
This appears related to #258 - what triggered the error was me searching for the Japanese city 'Fukuoka'. Apparently when the city isn't found, the error "There is a problem with your internet connection" is displayed (instead of something more reasonable like: "No city found").

I reseached for the city which worked previously ('Montreal') and it started working normally again.

**Comment by robinpaulson** [comment]
We should probably use better error messages, this is misleading.

**Comment by robinpaulson** [comment]
Check #316 for the issue which collates all similar issues.
