### ISSUE TITLE
New screenshots for readme

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#295]
The screenshots in the readme are a bit out of date; is anyone prepared to make 3 shots we can use, from the latest version? You could upload them to imgur, then submit a PR for the updated readme with new links.

**Comment by robinpaulson** [comment]
We've made a few updates to the software in the last 14 months. Is anyone interested in adding newer screenshots? The graphs have probably changed the most.

**Comment by sotpapathe** [comment]
| | | |
| :-: | :-: | :-: |
| ![Forecastie_main_20200509](https://user-images.githubusercontent.com/16228680/81476873-0a231680-921d-11ea-9ff9-cf737075c1f4.png) | ![Forecastie_graphs_20200509](https://user-images.githubusercontent.com/16228680/81476871-08f1e980-921d-11ea-8da6-edaec422336b.png) | ![Forecastie_map_20200509](https://user-images.githubusercontent.com/16228680/81476874-0abbad00-921d-11ea-968c-4efd1845b123.jpg) |

I converted the map screenshot to JPEG to achieve a smaller file size (194 KiB vs 634 KiB). The other images were smaller as PNGs. Here is the map screenshot in PNG in case it is needed:

[Forecastie_map_20200509.png](https://user-images.githubusercontent.com/16228680/81476875-0b544380-921d-11ea-81de-9a1e3c48ec50.png)

Why not put the screenshots inside the repository instead of hosting them on Imgur? The would be an extra 314 KiB but we would have everything in one place and not rely on Imgur for the README to show properly.

**Comment by sotpapathe** [comment]
Forgot to mention that the license for the screenshots is [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) (practically public domain).

**Comment by robinpaulson** [comment]
> Why not put the screenshots inside the repository instead of hosting them on Imgur?

yep, this is a very good point. When we get new screens, I'll store them in the repo. would you be able to make some?

**Comment by robinpaulson** [comment]
Oh, these are new! Thanks for that, I just noticed the date. Cheers
