### ISSUE TITLE
add snow graph

### ISSUE THREAD

**Issue by MisterY** [martykan/forecastie#296]
Turns out that snow and rain graphs are separate and unrelated. It is getting significant to see both now that the Winter is here.

**Comment by robinpaulson** [comment]
Hmm, good point. Worth considering. Would you be able to look through the OWM API and maybe suggest a line of code or two? The existing code for rain graphs would probably be a good start, it should only need a line or two changing.

**Comment by martykan** [comment]
I would combine the two, into a percipitation graph.

**Comment by MisterY** [comment]
Here are some quick references to what the Open Weather API offers. The relevant documentation is [here](https://openweathermap.org/forecast5).

JSON results include rain and snow separately:

```
list.rain
    list.rain.3h Rain volume for last 3 hours, mm
list.snow
    list.snow.3h Snow volume for last 3 hours
```

The XML results come as precipitation, with the type attribute: `<precipitation value="5%" unit="3h" type="rain"/>`, as per docs:

```
forecast.precipitation
    forecast.precipitation.value Precipitation volume for the last 3 hours, mm
    forecast.precipitation.unit Period of measurements. Possilbe value is 1 hour, 3 hours.
    forecast.precipitation.type Type of precipitation. Possible value is rain, snow.
```.

**Comment by robinpaulson** [comment]
As a first cut, we could copy-and-paste one of the other graphs, change the source and colour of the graph and we're away. Later on we think about combining (a separate sub-project I think) the charts into one. Maybe add a check box in the options to show the graph or not - there are enough places with no snow ever to make this worthwhile.

@MisterY as for having two apps doing the same thing, there are multiple reasons why a person might contribute to some software, or any project which builds something. Utility is one of them, but we shouldn't ignore the human desire to make a mark on the world, to let others know how we think and feel. Maslow's Hierarchy of Needs is a good start for understanding these impulses, particularly self-actualisation, which I think is relevant here. As more and more people work on a project/software, the effect one person can have diminishes. As that happens, it is more likely the next person who wants a weather app will start a new project rather than have minimal/zero impact on an existing project. So, yes we are reinventing what exists, but that may not be the most important thing.

Eric Raymond also talked about this from a slightly different angle when he discussed why people get involved; see CATB and the part about a sports car or deer antlers for more info.

**Comment by robinpaulson** [comment]
Well, looking through the code, it appears we have a snow graph already:
https://github.com/martykan/forecastie/blob/master/app/src/main/java/cz/martykan/forecastie/activities/GraphActivity.java#L301

It appears to say that if there is no rain, display the snow fall.

I wonder if we could make that more clear, say by also changing the title of the graph?

**Comment by robinpaulson** [comment]
I'm going to close this, as it's been superseded by #397. This comment will ensure the two issues are linked, meaning we keep the discussion and other information referenced.
