### ISSUE TITLE
Notification on exceptional weather events

### ISSUE THREAD

**Issue by bas080** [martykan/forecastie#345]
I would like to be notified when weather changes in a way that requires me to take action or change my behavior.

Example is a change in temperature that requires me to wear a jacket or just a T-shirt.

**Comment by Currrupted** [comment]
I agree! In my opinion this is a very important feature. Many professional and government-funded applications are using this already to distribute warnings for extreme weather and hazards.

I am not sure if I understood what you have in mind exactly. Should this just offer users some advice when the weather changes drastically and exceptionally? One other example would be a warning of ice/glaze, when the temperature drops shortly after rain and general wetness.

What I could think of are serious warnings for natural disasters or other risks because of weather. For example, the application could notify people of possible heat waves, storms or hurricanes. For this however it would probably be necessary to connect to local agencies and weather providers.

Both features would be nice to have imo

**Comment by bas080** [comment]
My wording could be better here. I agree that notifications for extreme weather events is a good idea.

On a lighter note, having notifications for (heavy) rain and relevant temperature changes would be useful for determining my outfit

**Comment by robinpaulson** [comment]
I agree that this would be useful, another user posted an issue some while back now (#192), but nobody has got around to working on it. If either of you are willing to code, I'll be glad to accept PRs. I'll close this and mark as dupe.
