### ISSUE TITLE
Wrong results when enter some specific words in searching city

### ISSUE THREAD

**Issue by dubYdub** [martykan/forecastie#407]
> The function of the city search works well when I entered the right city name. However, when I try to search with some specific words, the application provided some strange results.

#### When I searched for "apple", two results were provided:
- Hugo, US
- Kingston, US

I thought they might be the location of Apple(company), but they are not.

#### Then I search for "Google" & “facebook”, it showed:
- JSOM 解析错误

#### When I searched for "queen", three results were provided:
- Boulder, US
- Tionesta, US
- Roaring Spring, US

Besides, "**king**", "**sun**", "**moon**" also produced multiple results that don't relate to their names.

![the search result of "apple"](https://github.com/dubYdub/thing/blob/master/forissue.png)

**Comment by robinpaulson** [comment]
I suspect this is mostly due to the search engine at OWM finding the "closest" (which may or may not be particularly close) match it can. In these cases of being given information which has no good answer, it gives us rubbish. Some possible things we could do:
1. Get OWM to improve their search engine
2. Add some sort of filter so users can only search for reasonable words
3. Add some intelligence which tells the users if there are no close matches when the search returns rubbish.
4. Do nothing.
Option 3. Sounds like an interesting project, but hard work. Options 1 and 2 sound hard/near impossible.
Option 4 sounds easiest, plus most users are unlikely to try putting in nonsense data anyway. If they do, what is the worst thing that can happen?

**Comment by robinpaulson** [comment]
As an aside, i'm surprised there aren't towns with the words queen, king, sun, apple and moon in their names. I used to live in "Kingston upon Hull", I'm not sure why that didn't show up.

Also:

![](https://s-media-cache-ak0.pinimg.com/736x/e2/88/e/e288e81a2221d0f393fda4d735dd57b2.jpg)

**Comment by robinpaulson** [comment]
I did some searching for the terms you suggested. Most worked, there appear to be several towns named Queen, Apple, etc.

"Facebook" and "Google" returned "Error parsing JSON", which I assumed you meant when you typed "JSOM". I'll add this to the list of bad error codes we are dealing with in #316 . Thanks for reporting.

**Comment by Lee-Carre** [comment]
I recently learned (via a mail exchange with staff) that OWM uses [GeoNames](//www.geonames.org/) ([map](//www.geonames.org/v3/)) for locations.

So, it would be sensible to first ensure that the GeoNames data is sanitised.
