### ISSUE TITLE
Recalibrate pressure chart

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#421]
Currently the pressure chart is a small squiggle in the middle of the chart, taking up a low proportion of vertical space, with little apparent differentiation between high and low. I think we should change the y-axis so the difference between values is easier to see. This is only a problem for inHg and kPa as far as I can tell, the others look great.

**Comment by robinpaulson** [comment]
@FridoDeluxe Given you did the original coding, do you think you might take a look at this? Cheers

**Comment by FridoDeluxe** [comment]
Of course I can take a look. Do you mean something like this?

![forecastie_pressure](https://user-images.githubusercontent.com/498537/71914855-cb9c2300-317a-11ea-9978-e7d08cb76263.png)

If I had tested with all units I would have noticed this before. For pressure it depends on the following restrictions:
- WilliamChart only supports integer values on Y-axis
- the Y-axis range for the pressure chart is calculated so that there are always five horizontal grid lines (introduced by me)
- all charts have a pretty general algorithm to calculated the Y-axis range, there is no special code for certain units

I think in this case it's always a balance between keeping the code as simple as possible on one side and considering all possible combinations of units and value ranges on the other side. Any suggetions how to fix it? Maybe reject the rule of five horizontal grid lines when the value range is <= three?

**Comment by robinpaulson** [comment]
Yes, that's the problem. I agree with all you say, I think this is the best solution:

> Maybe reject the rule of five horizontal grid lines when the value range is <= three?

**Comment by FridoDeluxe** [comment]
The temperature chart is contructed with the very same rules, also always five grid lines. But the units Celcius, Fahrenheit and Kelvin shoud make an almost constant temperature for five consecutive days less likely. So I'd change only the pressure chart, okay?

**Comment by robinpaulson** [comment]
> So I'd change only the pressure chart, okay?

Yes, I agree.

**Comment by robinpaulson** [comment]
I got the new version today, still the same problem with inhg as the units. I wonder if this is even fixable with William chart and integer only y axis units?

**Comment by robinpaulson** [comment]
Kpa units appear fine

**Comment by FridoDeluxe** [comment]
> I got the new version today, still the same problem with inhg as the units.

**inHg** looks fine for me, could you provide a screenshot?

**Comment by robinpaulson** [comment]
@FridoDeluxe Here we go:

![Screenshot_2020-03-21_23-07-36](https://user-images.githubusercontent.com/1186107/77224321-4e088080-6bc9-11ea-8bfe-f42dd73e8cbe.png)

**Comment by robinpaulson** [comment]
This screenshot shows a wider than usual range of pressure values; some days it's hopeless trying to divine any meaning from the chart.

**Comment by FridoDeluxe** [comment]
Thanks for the screenshot. I don't think we can fix this: WilliamChart allows only an integer scale on the y-Axis, and the small value range of `in Hg` is not really compatible with it.

In my opinion a perfect support for `in Hg` is not worth the effort of changing the chart library.

**Comment by robinpaulson** [comment]
Yes, I agree. I'll close, maybe we get another idea in the future of how to fix it.
