### ISSUE TITLE
Map view - unexpected bottom bar overlay

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#431]
See screenshot. With portrait orientation, the Android virtual keys are over the bottom button bar.

Also, the top title bar is empty.

I notice now that the whole app does not have a title bar; I am not sure if this is a recent change. I think this could be related.

![Screenshot_20200122-211401](https://user-images.githubusercontent.com/12466054/72930626-9f78c880-3d5c-11ea-9364-9d889dab1f6a.jpg)

**Comment by robinpaulson** [comment]
A title bar, as in at the top of the screen? I don't recall there ever being one there. Perhaps you would be willing to do a quick check through previous screenshots here in the issues?

I don't know much about the virtual/soft keys, I've never used a phone which has them. This sounds like something the system would handle, rather than an individual app.

**Comment by FridoDeluxe** [comment]
I can't reproduce this problem with the latest Forecastie version (1.13.1). Tried landscape, portrait and switched between them, but there is always no title bar and the soft keys are on the bottom of the phone (means right/left in landscape) on standard LineageOS.

@igor-cali I remember you are using EMUI and a custom theme, maybe this setup handles the placement of soft keys differently in some cases?

**Comment by igor-cali** [comment]
Thanks @FridoDeluxe. You remember correctly.
Anyway, the behaviour in my device does not improve even if default theme/font is active.

**Comment by FridoDeluxe** [comment]
@igor-cali It was just an idea ... You could go back in history and try to determine when this bug appeared first (find the commit that introduced this error). Apart from that I have currently no idea how to find a solution ...

**Comment by igor-cali** [comment]
I tried to mitigate this, with no success (using `android:fitsSystemWindows`).
A possible cause is that the BottomBar is attached to the webview after the creation.

**Comment by sotpapathe** [comment]
I also experience the same issue on Android 7.1.2 (LineageOS with microG). I noticed that while the map view starts the same way as in the screenshot by @igor-cali , when tapping on any of the buttons on the bottom the bottom bar moves above the virtual keys. However the black top bar remains and the background of the virtual keys is blue instead of black which is normally the case.

| ![Screenshot_20200323-142257](https://user-images.githubusercontent.com/16228680/77316741-a13a1a80-6d12-11ea-8404-4806c52ceaed.png) | ![Screenshot_20200323-142305](https://user-images.githubusercontent.com/16228680/77316758-a5663800-6d12-11ea-98ad-37bc4eb78849.png) |
| - | - |
| Before tapping | After tapping |

**Comment by robinpaulson** [comment]
Erk, that's not so good

**Comment by robinpaulson** [comment]
> A possible cause is that the BottomBar is attached to the webview after the creation.

Would it be better to attach the bottombar *before* the creation? Is that what you're implying?

**Comment by igor-cali** [comment]
> > A possible cause is that the BottomBar is attached to the webview after the creation.
> 
> Would it be better to attach the bottombar _before_ the creation? Is that what you're implying?

@robinpaulson n Do you know where in the code the bottom bar is attached? Also, I think the top black bar should be removed.

**Comment by robinpaulson** [comment]
I'll take a look, see what I can find. I agree with the second part, yes we should remove it. I'm not sure why it's there, it's not on my device - Samsung Galaxy S3 with physical buttons. I wonder if it's an artefact of the soft keys?

**Comment by robinpaulson** [comment]
I see both you and sotpathe have the problem and both have phones with soft keys.

**Comment by FridoDeluxe** [comment]
Just an information: I have soft keys, but experience no problems with the bottombar and I also don't see the black bar on the top (LineageOS 16).

**Comment by igor-cali** [comment]
I tried to recap my understanding [here](https://pastebin.com/raw/NjvXVh5K).
Please review as necessary.
It looks like there is no enough information to identify a possible enabler of this issue.

**Comment by FridoDeluxe** [comment]
My device is a LG G2 with 5.2" screen, Android 9 (LineageOS 16.0) and currently Forecastie version 1.13.2. But I can't remember any problems with the layout of the map view.

I can image that for most users the map looks alright. Otherwise there would be another bug report already, because it really seems to be an annoying bug. The respective library [BottomBar](https://github.com/roughike/BottomBar) is archived, maybe replacing it by an supported alternative (`BottomNavigationView`) can fix the problem?

**Comment by robinpaulson** [comment]
@FridoDeluxe How do you feel about investigating that replacement? I'm not keen on relying on unmaintained libraries.

Erk, 2.5 years since last commit!

**Comment by robinpaulson** [comment]
Perhaps we should do an audit of all our dependencies?

Actually I thought Github automatically pulled up repos with security alerts. Hmm, but probably not old repos with no alerts. Which arguably constitutes a security risk, if not an alert.

**Comment by FridoDeluxe** [comment]
> @FridoDeluxe How do you feel about investigating that replacement? I'm not keen on relying on unmaintained libraries.

I could do that, but currently I'm lacking time. Also I think it's better when @igor-cali investigates a replacement because he can determine at the same time if it fixes the bug.

**Comment by igor-cali** [comment]
Replaced with BottomNavigationView (see commit above).
I don't know how to set the bottom bar solid background color according active theme (`setTheme()` has no effect).

**Comment by robinpaulson** [comment]
We may have to open another issue if the solid background colour is a problem; I'll wait for the release and then decide.
