### ISSUE TITLE
Do we accept a new icon proposal?

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#470]
A new user has very kindly put time and effort into designing new icons for the project. I would like to hear from others what you think of them and whether we should use them. The changes can be seen in https://github.com/Karandeep98/forecastie

Also: see #469

**Comment by Karandeep98** [comment]
Yes go for it! 👍

**Comment by sotpapathe** [comment]
| Old | New |
| :-: | :-: |
| ![old square icon](https://raw.githubusercontent.com/martykan/forecastie/master/app/src/main/ic_launcher-web.png) | ![new square icon](https://raw.githubusercontent.com/Karandeep98/forecastie/master/app/src/main/ic_launcher-web.png) |
| ![old circular icon](https://raw.githubusercontent.com/martykan/forecastie/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png) | ![new circular icon](https://raw.githubusercontent.com/Karandeep98/forecastie/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png) |

The icons in question.

I really like the new design but I'd rather have flat colors instead of gradients. I think the gradients add too much information and there's already quite a bit of detail on the icons.

I take it these icons are your own creations @Karandeep98 ? I'm asking because we are considering icon licenses in #450 and we need to know who the copyright holder is.

**Comment by FridoDeluxe** [comment]
I hope it's okay that I embed the proposed logo, so everybody knows what we are talking about:

![logo](https://raw.githubusercontent.com/Karandeep98/forecastie/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png)

**Comment by FridoDeluxe** [comment]
Thanks for the comparison table @sotpapathe !

Some quick thoughts about it. In my opinion in general a good app logo should
1. be unique and easy to recognize
2. integrate nicely with the rest of the app (although the current logo is not special at all it reuses the classic theme color and is as minimal as the app layout itself)
3. last but not least: be beautiful :-)

Forecastie is a voluntary driven project lives from many small "not coordinated" improvements, we can't wait for a perfect layout and logo concept. Still the logo as the "face" of an app is important and we should think twice before changing it.

Concerning the proposed design of @Karandeep98: It looks really nice, also the color choice is modern. And the diagonal split between sun and rain is a great idea. And of course thank you for taking the time and effort to propose a new logo!

On the other hand the logo is maybe a bit too sophisticated and a bit low-contrast, I'm not sure if it stands out against other app icons. But I don't have an idea right now how to make it more concise ... Also it does not pick up the design language/colors of the app. (Maybe it's possible to use the shape of the Forecastie weather icons?)

So in my personal opinion the logo itself looks great! But I don't know if just changing the logo really improves the overall Forecastie experience. So @sotpapathe and I had similar thoughts - looking forward to hear other opinions!

**Comment by FridoDeluxe** [comment]
@Karandeep98 two rather technical questions:
1. Could you also submit the original files? (It's always nice to have the "source" files and not only the rendered logo result)
2. Are different logo versions necessary (`round` and `foreground`)? I wouldn't use a round logo, I think square (or true adaptive logo) looks better (whatever actual shape choosen by the user).

**Comment by FridoDeluxe** [comment]
Looks like @Karandeep98 lost interest ...

**Comment by FridoDeluxe** [comment]
Inspired by our discussion about a good new Forecastie icon I a bit played around and tried to include the Forecastie colors and icon shapes:

| Filled | Outlines |
|---|---|
| ![ic_launcher](https://user-images.githubusercontent.com/498537/82753768-8e9e9900-9dc8-11ea-8371-c7c316c5c8a3.png) | ![ic_launcher-2](https://user-images.githubusercontent.com/498537/82753772-8fcfc600-9dc8-11ea-8faa-a9f84e807fd6.png) |
| ![ic_launcher_round](https://user-images.githubusercontent.com/498537/82753769-8f372f80-9dc8-11ea-9f19-8364fa3ff723.png) | ![ic_launcher_round-2](https://user-images.githubusercontent.com/498537/82753770-8fcfc600-9dc8-11ea-816e-88a737677be8.png) |

It's just an idea, not a perfect icon yet (margins and shadows need to be adjusted). But it looks like any generic weather app, not unique at all ...

The more I think about the icon topic I come to the conclusion that the current simple cloud is a really good icon. Maybe we could change the background color (because the fresh blue is now the app's default color?) but apart from that in my opinion we should keep it.

**Comment by robinpaulson** [comment]
> the current simple cloud is a really good icon

On a similar note, I'm wary of joining in with the "arms race", whereby each app author tries to make their icon stand out from all others, thus producing a screen of garish, bright colour which helps nobody and contributes to overwhelming the user. Understated, subtle and restrained have their place.

**Comment by robinpaulson** [comment]
OK, I'm going to close this. I was leaning slightly towards accepting it, but @sotpapathe and @FridoDeluxe have swayed me slightly the other way, so given there's not been a huge interest in the question, i'll say to @Karandeep98 

It's much appreciated you taking the time and effort to come up with this, and for suggesting it, but I'm going to decline for now. Please do stay involved with the community, I'm sure there will be other design-related sub-projects we require in future.

Cheers!
