### ISSUE TITLE
Windows 10 version 

### ISSUE THREAD

**Issue by DGMurdockIII** [martykan/forecastie#478]
Yes I know that this may be long shot but I would love to see a window 10 version of the app I would love a UPW
https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide

**Comment by FridoDeluxe** [comment]
My optinion: This will not happen, because it's a different development process (other tools, other programming language) and actually means to build a completely new application. Also developing for a rather closed system like the Windows Store doesn't correspond well to the open source idea of Forecastie.

Maybe you are looking for something like this: https://www.microsoft.com/de-de/p/simpleweather-a-simple-weather-app/9nkc37bc8srx ?

**Comment by robinpaulson** [comment]
Exactly, well put. I'm sure there are many projects as good or better than Forecastie for Windoze.

**Comment by DGMurdockIII** [comment]
If there are some alternatives then what are they

**Comment by FridoDeluxe** [comment]
If the weather app linked above is not suitable for you then you should continue to search for alternatives on your own. This is not the place to discuss Windows apps.
