### ISSUE TITLE
Split translation strings into multiple strings files

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#492]
As per https://github.com/martykan/forecastie/issues/364#issuecomment-651622998

This will make them easier to manage. There are multiple ways we could group them:
1. according to the groups I've already laid out in #455 
2. according to the activity/fragment which uses them
3. ???

All suggestions welcome.

**Comment by fAntel** [comment]
Both option will face situation when string from one file is used on several screens or in several groups. I like second option and in addition I think a good option would be to put aside non-translatable strings in separate file or files (for example keys for preferences).
My experience says that no matter which option will be used, it's easier to find a string by searching all the files than try to remember where it lays. Therefore, it should be just highlighted which approach is used so that new strings are add with this approach in mind.

**Comment by robinpaulson** [comment]
> string from one file is used on several screens or in several groups.

yeah, this thought crossed my mind too

> put aside non-translatable strings in separate file or files

yep, good thinking

option 3: put the strings in alphabetical order, maximum 20 (or whatever) to a file

**Comment by fAntel** [comment]
I don't see the point in option 3. The goal of splitting string, as I see it, is to protect us from accidental reordering of strings which can complicate the life of translators.

**Comment by robinpaulson** [comment]
@fAntel 

Sure, that sounds like good reason not to go for (3), I guess was doing a brain dump more than proper thinking

**Comment by robinpaulson** [comment]
> put aside non-translatable strings in separate file

done. now to split the rest of the strings into multiple files

**Comment by robinpaulson** [comment]
I split the strings (English only so far) in way that felt reasonable to me, but it's probably arbitrary. We'll see how it goes before changing the other languages, maybe it wasn't such a good choice I did.
