### ISSUE TITLE
Graph display bug

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#507]
See the attached image for details

**Comment by robinpaulson** [comment]
![](https://i.imgur.com/qbZZZ9q.png)

**Comment by robinpaulson** [comment]
Wednesday's temp is 8.6 degrees but the minimum point on the scale is 9

**Comment by robinpaulson** [comment]
This is likely an edge-case which occurs only when the temperature (and probably humidity, wind speed or pressure) for the last forecast time is lower than all the other forecast times in the 5 day period.

Question: when we calculate the lowest temperature, in order to set the lowest extent of the chart scale, does it include the value for the last forecast slot in the data? Perhaps the code doesn't iterate over all values in the relevant array? That appears at first glance to be the most likely explanation.

@FridoDeluxe Given you've done a decent amount of work on the graphs recently, would you be able to answer this?

**Comment by FridoDeluxe** [comment]
> Or perhaps there is a rounding error? If we round 8.6 to the nearest integer, we get 9. I think that's unlikely, someone would have spotted it previously.

Actually I've noticed this graph behaviour already multiple times. On the one hand I wondered if this is a bug, on the other hand I aesthetically liked it (similar to [overshoot](https://en.wikipedia.org/wiki/Overshoot_(typography)) in typography).

I had a quick glance at the code and indeed it seems to be caused by rounding (the rounding formula is a bit more complex and needs to consider both min and max values at the same time, that's why such display bugs happen seldomly). I'll try to work on a fix in the next days ...

**Comment by robinpaulson** [comment]
Fascinating wp page, thanks for the link. I agree now you mention it, there is a certain aesthetically-pleasing quality to it. Maybe we could leave it....

**Comment by FridoDeluxe** [comment]
> Maybe we could leave it....

Theoretically we could leave it. But actually this behaviour is not intended and not really coordinated. The line in the screenshot above interferes with the axis labels, it rather looks like a bug.

In #522 I improved the min/max calculation for temperature and pressure (in case pressure values are no integers), the other graphs should not be affected.

**Comment by robinpaulson** [comment]
Closed, fix due in the next release
