### ISSUE TITLE
Update Play Store Version (including migrate to later targetsdk)

### ISSUE THREAD

**Issue by radasbona** [martykan/forecastie#509]
Play Store Version is strongly outdatet. There is still the "location defaults back to London" bug.
Please update.

(My Work Phone is restricted, no unknown sources no root..... So i'm forced to use play store.)

**Comment by robinpaulson** [comment]
Yeah, @martykan handles that.

**Comment by robinpaulson** [comment]
As an aside, once I figure out how Github actions work, we'll be publishing an .apk here. I assume you can install that without root/unknown sources enabled? I realise it's not the same as updating GPlay, another option is all.

**Comment by fAntel** [comment]
I think it's important to keep Forecastie up to date in Google Play. Forecastie is a good app but I can't to recommend it for my relatives and friends with old Android phones because it's unsafe to allow all apps to install apk from unknown source. I've installed F-Droid recently because in new Android versions rights to install apk can be done only to apps specified by the user.

But even the latest version of Forecastie (15.6) can not be uploaded into Google Play because of target sdk. Forecastie targets Android 8 but from November 2019 Google Play requires targeting Android 9 and it will be increased to Android 10 in November 2020. We should update target sdk version prior to update Forecastie in Google Play.

**Comment by radasbona** [comment]
"I assume you can install that without root/unknown sources enabled?"

Unfortunately not, everything but play store is a unknown source. On every (non rooted) Android Phone. 

So I'm really forced to use playstore. 

My own mobile is not the problem, there is fdroid installed.


Am 1. September 2020 04:06:24 MESZ schrieb robinpaulson <notifications@github.com>:
>As an aside, once I figure out how Github actions work, we'll be
>publishing an .apk here. I assume you can install that without
>root/unknown sources enabled? I realise it's not the same as updating
>GPlay, another option is all.

**Comment by robinpaulson** [comment]
> Android 8 but from November 2019 Google Play requires targeting Android 9 and it will be increased to Android 10 in November 2020. We should update target sdk version prior to update Forecastie in Google Play

I'm not sure entirety what this means, or the consequences of it. Could you give me s little more info, or a link? Thanks

**Comment by fAntel** [comment]
> > Android 8 but from November 2019 Google Play requires targeting Android 9 and it will be increased to Android 10 in November 2020. We should update target sdk version prior to update Forecastie in Google Play
> 
> I'm not sure entirety what this means, or the consequences of it. Could you give me a little more info, or a link? Thanks

Yes, sure. Idea is simple, all apps give to Android information about which maximum Android version they know (this is "target sdk version") and Android based on this info can change some behavior like require new permissions and so on. For the last few years security and privacy of Android OS has been increased and Google tries to make developers live with that by updating minimum target sdk version for new apps or updates for existing apps.
So, to update Forecastie in Google Play we need to update target sdk version in app/build.gradle from 27 (Android 8) to 28 (Android 9) or to 29 (Android 10). After update target sdk version for Forecastie on Android 8 or above behavior will be able to change and some features may break.
https://developer.android.com/distribute/best-practices/develop/target-sdk - this is brief information of new features and migration to Android 9/10.
https://developer.android.com/about/versions/pie/android-9.0-changes-28 - this is list of changes for apps targeting Android 9 (Android SDK 28)

I can do it by myself because I've already read all this during work but it will take some time.

**Comment by robinpaulson** [comment]
@fAntel Cheers for the research, that's useful to know. Does this have any negative consequences for lower API version, i.e. prevent the app from working on them?

I'll check out the PR.

**Comment by robinpaulson** [comment]
New release out today, with these changes in, built by Github. Check the releases page for the latest arm binary.

**Comment by robinpaulson** [comment]
OK, that revealed a whole load of other bugs. Gradle is now much less forgiving on unescaped apostrophes and demands "&gt;" rather than ">". I fixed those, will do another release in a few days.

@martykan This should be Google-compliant now, upload to GPlay if you wish.

**Comment by robinpaulson** [comment]
> it will be increased to Android 10 in November 2020

given this is the case, perhaps we should prepare now? november is 6 weeks away. @igor-cali given you did the upgrade to android 9 compatibility, would be you be able to take a look at this? cheers

**Comment by igor-cali** [comment]
> > it will be increased to Android 10 in November 2020
> 
> given this is the case, perhaps we should prepare now? november is 6 weeks away. @igor-cali given you did the upgrade to android 9 compatibility, would be you be able to take a look at this? cheers

@robinpaulson I upgraded to 9 as a first step. Of course I can check for the upgrade to Android 10. Prior to do this, can you check if there is still an issue for Play Store still not updated to 9?

**Comment by robinpaulson** [comment]
@igor-cali I'm not sure what your last question means?

**Comment by igor-cali** [comment]
I mean, this issue looks still unresolved, besides the update to Android SDK 9 is now merged in the code.

**Comment by robinpaulson** [comment]
Ah, I see. Yes, as far as I can see from the notes by @fAntel , we've done what is required. Martykan handles the Google Play side of things, I'll leave that to him to upload.

**Comment by robinpaulson** [comment]
I copied the few lines necessary to upgrade to Android 10/SDK29 from @igor-cali 's aborted PR. I'll push a new release soon with all the behind-the-scenes changes we've made. We're ready for a minor version increment, v1.16 here we come!

**Comment by robinpaulson** [comment]
Closing, we've done the sdk upgrade.

**Comment by radasbona** [comment]
Thanks. But Play Store Version is still from 03 2019. 



Am 24. September 2020 15:13:12 MESZ schrieb robinpaulson <notifications@github.com>:

**Comment by robinpaulson** [comment]
> Thanks. But Play Store Version is still from 03 2019.

yes, @martykan looks after the google play part of things. he'll get to it when he can.

**Comment by radasbona** [comment]
Ok. Thank you.

**Comment by radasbona** [comment]
6 month passed and nothing happens. 🤨

**Comment by robinpaulson** [comment]
Well we updated the sdk and migrated to androidx, so not nothing

**Comment by martykan** [comment]
Hello, I just uploaded the latest version. I set up some scripts to speed this up, so in the future I will keep it more up to date

**Comment by radasbona** [comment]
It's up. Thank you.

Am 9. Februar 2021 16:55:29 MEZ schrieb "Tomáš Martykán" <notifications@github.com>:
