### ISSUE TITLE
London fixed when app is restarted

### ISSUE THREAD

**Issue by initenit** [martykan/forecastie#611]
When I restart the app, the weather information is fixed to London. Can I change it to current city or make some settings that people can setting the first city?

**Comment by robinpaulson** [comment]
Yes, it will do this already. Try the "Detect Location" feature.

**Comment by initenit** [comment]
It only works when I push the button. I want it works automatically when I start the app.

**Comment by Lee-Carre** [comment]
I recall the `Update location in background` configuration option. Might be worth checking if this is enabled in your instance, @initenit .

A sensible implementation I've encountered occasionally in other apps, is that they *passively* get the location, and silently self-update based on that.

Thus, battery-saving when the user is likely remaining in the same area (or otherwise unconcerned about their device knowing current location) yet uses recent location info when something else is requesting location info for other reasons.

For users who then want Forecastie (or similar-implementation apps) to always have recent info; keep the GNSS receiver enabled (such as by using [mirfatif/MyLocation](http://www.github.com/mirfatif/MyLocation) (available via F-Droid) ).

**Comment by robinpaulson** [comment]
@Lee-Carre This is really interesting, thanks. I realise now that I had a wrong interpretation of what "passive location" meant.

**Comment by Lee-Carre** [comment]
@robinpaulson

> I had a wrong interpretation of what "passive location" meant.

As did I, in the context of Android. I was prompted to think of something like an inertial system or maybe passive sonar. Ironic that prior knowledge was a disadvantage in this case.

For what Android means by *passive*, then some derivative of the word ‘cached’ would have been far less ambiguous, I feel. But, alas.

Anyway; glad you found the suggestion useful.

One advantage of querying the passive provider is that you can (within reason) be less careful about interval, timeout, and accuracy.
Off the top of my head:
* interval of 5-15 minutes (to determine if moving a significant distance and need to query weather data for a different location; else a different approach would be to use the accelerometer)
* timeout of 5-20 seconds (enough to allow for a (reasonably) fine-grained fix, but short enough to account for the device being indoors and thus may never get a GNSS fix)
* accuracy up to maybe 500-1000 metres (only need to know the general area). If the user is running an app which keeps the GNSS receiver active (like a navigation app would) then the accuracy of the supplied fixes should be much better (than 500 metres) anyway.

Should be good enough for the purposes of knowing which area to request weather info for. However, adjust as you see fit.

Then can simply leave that looping in the background (or waiting to be sent an event; however the internals work), and the results are auto-magic with a lot of use-cases handled gracefully (without overly complex code or killing the battery). Everyone wins.

**Comment by Lee-Carre** [comment]
See also [android/location-samples](http://github.com/android/location-samples).
