### ISSUE TITLE
[FR] widget planned?

### ISSUE THREAD

**Issue by ildar** [martykan/forecastie#9]
.

**Comment by martykan** [comment]
Yes, I am working on it, but it's not yet going to be in 0.4.

**Comment by logos88** [comment]
Yeah, a widget would be great! I leave a few examples of widgets I think are great if they help as some kind of inspiration

YoWindow:
https://lh4.ggpht.com/SanhGmbQF8sMzFE1FyRCraLdOd_hiNZ0RQvGdT-9us7q7DnwXs87VyheElwA7ZmeogQ=h900

Eltiempo.es
https://www.google.com/imgres?imgurl=http://www.elandroidelibre.com/wp-content/uploads/2013/11/eltiempo.es-widget.png&imgrefurl=http://www.elandroidelibre.com/2013/11/la-aplicacion-de-eltiempo-es-se-actualiza-para-ios-pero-en-android.html/eltiempo-es-widget&h=958&w=542&tbnid=trTuYNzXtecw5M:&docid=9utH68zEhs_6CM&ei=n6-LVtviO8vjUeeRraAC&tbm=isch&client=firefox-a&ved=0ahUKEwibrsuEz5LKAhXLcRQKHedICyQQMwgcKAAwAA

I love the one from YoWindow because it shows you the evolution of the weather the same day and the next ones in just one sigh. I like the little one of the eltiempo.es because you can see the forecast of the week in little space and if you need to know more ou can push the widget and open the app.

Great job with the aplication!! :)

**Comment by martykan** [comment]
Right now I only have a widget with current weather, but I'll make one with future forecast later on.

<img src="http://i.imgur.com/4MR23ca.png" width="250">

**Comment by RwyAPx7XFnS8J7rCdVaY** [comment]
Thanks for the work you've been doing. The widget looks good on your device, but on mine is a bit unaligned I don't know if it's because is a tablet.

![1](https://cloud.githubusercontent.com/assets/16533301/12261198/81eb3186-b917-11e5-84a8-c0f5fbe62cb6.png)

![2](https://cloud.githubusercontent.com/assets/16533301/12261206/8619fb84-b917-11e5-9afa-e3b0128bd402.png)

**Comment by dbolton** [comment]
On my screen (probably narrower than yours), the widget at the default size shows the weather icon only (no temperature or refresh button). If I vertically expand the widget to three rows it shows the full information (except the weather icon overlaps with the end of the city name).

**Comment by martykan** [comment]
Yeah, I will rework the layout so it's more flexible.

**Comment by ildar** [comment]
thanks for the widget, I'll open more issues on it ;)
Meanwhile, please close this issue as soon as you desire.
